Allow more fine grained control of output format
gvansickle/ucg pull request #145
Opened 2024-12-15 05:07 UTC by wlandry

This adds the options

- --null
- --[no--]with-filename
- --[no--]line-number

to allow more fine grained control of the output.  It also regularizes the tty behavior by making it set these options, rather than checking for a tty and then overriding behavior at the last moment.

There is also a bit of cleanup of unused enums and a fix to includes.

Default output should remain the same.

Please let me know if this is the kind of thing you want, or if you rather go in a different direction.

2024-12-16 23:24 UTC, gvansickle commented
Hi @wlandry , thanks for the PR!  Taking a look at it now.

2024-12-18 23:02 UTC, gvansickle requested changes
Yeah, I definitely like the direction of these changes @wlandry .  See the couple minor review comments.

2024-12-19 04:52 UTC, wlandry commented on src/ArgParse.cpp
> + * Copyright (C) 2022 Free Software Foundation, Inc.
This is intentional.  I lifted the help text directly from GNU grep.

2024-12-19 05:15 UTC, wlandry commented on src/ArgParse.cpp
> +		{ OPT_LINE_NUMBER, ENABLE, "n", "line-number", Arg::None, "Print the line number of each match (default)."},
I removed the -n short option from --no-recurse.

2024-12-19 05:15 UTC, wlandry commented on src/ArgParse.h
> +	/// also set m_line to true.
Fixed

2024-12-19 05:16 UTC, wlandry commented on src/MatchList.cpp
> -	// The only real difference between TTY vs. non-TTY printing here is that for TTY we print:
I put the comment in ArgParse.cpp where I check for tty.

2024-12-19 05:16 UTC, wlandry commented on src/OutputTask.cpp
> -	// Determine whether to enable color or not.
I incorporated this comment in ArgParse.cpp where I check for tty.

2024-12-19 05:18 UTC, wlandry commented
I rebased and push the fixed version.

2024-12-23 00:39 UTC, gvansickle requested changes
Looks great @wlandry .  See my one remaining change request, when that's resolved I'll merge your PR.  Thanks!

2024-12-23 00:39 UTC, gvansickle commented on src/ArgParse.cpp
> + * Copyright (C) 2022 Free Software Foundation, Inc.
Ok, looks like you only took the "man grep" text regarding --null from grep, I don't see anything else added from grep.  I hate to say it, but I think this should be changed in one, maybe two ways:
1. Remove the copyright line.  Per GNU/FSF themselves, it's not needed even if you're doing a direct copy/paste, see https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility .  We're GPL3 and grep is GPL3+.
2. Shorten/reword the --null help text so it's not a copy/paste.

I'm OK with just # 1, and would merge it, everything else looks good.

2024-12-23 03:54 UTC, wlandry commented
I did option 2 and shortened the help text.

2024-12-27 23:33 UTC, merged

2024-12-27 23:33 UTC, gvansickle commented
PR merged, thanks @wlandry !